#!/bin/ksh
# Document delivery

# For logging
echo "===================="
date

/m1/voyager/ucladb/sbin/Pcircjob -j26
# Creates these files
#ls -l /m1/voyager/ucladb/rpt/opacrequests.OE_LN.out
#ls -l /m1/voyager/ucladb/rpt/opacrequests.OE_PH.out

# Get voyager environment, for vars and for cron
. `echo $HOME | sed "s/$LOGNAME/voyager/"`/.profile.local

# Endeavor set NAME=`hostname`, but when userid voyager sends mail, we
#    prefer to put the comment field from /etc/passwd into the From: header 
unset NAME

/m1/voyager/ucladb/local/docdeli/docdeli.pl

# Creates this file
#ls -l /m1/voyager/ucladb/rpt/transactions.txt

# Clean up old files
## Anything more than 14 days old
find /m1/voyager/ucladb/rpt -type f -name "transactions.txt.*" -mtime +14 -exec rm {} \;
## Any empty files older than today
find /m1/voyager/ucladb/rpt -type f -name "transactions.txt.*" -mtime +0 -size 0 -exec rm {} \;
